In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('Healthcare.csv')

In [3]:
print("Original Data Preview:")

Original Data Preview:

In [4]:
display(df.head())

,Patient_ID,Age,Gender,Symptoms,Symptom_Count,Disease
0,1,29,Male,"fever, back pain, shortness of breath",3,Allergy
1,2,76,Female,"insomnia, back pain, weight loss",3,Thyroid Disorder
2,3,78,Male,"sore throat, vomiting, diarrhea",3,Influenza
3,4,58,Other,"blurred vision, depression, weight loss, muscl...",4,Stroke
4,5,55,Female,"swelling, appetite loss, nausea",3,Heart Disease

In [5]:
df['Symptoms'] = df['Symptoms'].str.split(', ')

In [6]:
df_cleaned = df.explode('Symptoms')

In [7]:
print("\nCleaned Data Preview (Symptoms are now separated):")

Cleaned Data Preview (Symptoms are now separated):

In [8]:
display(df_cleaned.head(10))

,Patient_ID,Age,Gender,Symptoms,Symptom_Count,Disease
0,1,29,Male,fever,3,Allergy
0,1,29,Male,back pain,3,Allergy
0,1,29,Male,shortness of breath,3,Allergy
1,2,76,Female,insomnia,3,Thyroid Disorder
1,2,76,Female,back pain,3,Thyroid Disorder
1,2,76,Female,weight loss,3,Thyroid Disorder
2,3,78,Male,sore throat,3,Influenza
2,3,78,Male,vomiting,3,Influenza
2,3,78,Male,diarrhea,3,Influenza
3,4,58,Other,blurred vision,4,Stroke

In [9]:
df_cleaned.to_csv('cleaned_big_data.csv', index=False)

In [10]:
print("Done! Check your folder for 'cleaned_big_data.csv'")

Done! Check your folder for 'cleaned_big_data.csv'